import { getAuthenticatedGoogleClient } from '@/lib/google-calendar';
import { NextResponse } from 'next/server';

export async function GET() {
    try {
        const calendar = await getAuthenticatedGoogleClient();

        // Create a test event usually "now"
        const start = new Date();
        const end = new Date(start.getTime() + 3600000); // +1 hour

        const res = await calendar.events.insert({
            calendarId: process.env.GOOGLE_CALENDAR_ID || 'primary',
            requestBody: {
                summary: 'TEST EVENT BLB',
                description: 'Generated by /api/google/test',
                start: { dateTime: start.toISOString() },
                end: { dateTime: end.toISOString() }
            }
        });

        return NextResponse.json({ success: true, link: res.data.htmlLink });
    } catch (e: any) {
        return NextResponse.json({ error: e.message }, { status: 500 });
    }
}
