import { createClient } from "@supabase/supabase-js";
import { normalizePlace } from "../utils/normalization";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error("Falten variables d'entorn (SUPABASE_URL o KEY)");
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const RawCSV = `nom,comarca
"Abella de la Conca","Pallars Jussà"
"Abrera","Baix Llobregat"
"Àger","Noguera"
"Agramunt","Urgell"
"Aguilar de Segarra","Bages"
"Agullana","Alt Empordà"
"Aiguafreda","Vallès Oriental"
"Aiguamúrcia","Alt Camp"
"Aiguaviva","Gironès"
"Aitona","Segrià"
"Alàs i Cerc","Alt Urgell"
"Albanyà","Alt Empordà"
"Albatàrrec","Segrià"
"Albesa","Noguera"
"Albinyana","Baix Penedès"
"Albons","Baix Empordà"
"Alcanar","Montsià"
"Alcanó","Segrià"
"Alcarràs","Segrià"
"Alcoletge","Segrià"
"Alcover","Alt Camp"
"Aldover","Baix Ebre"
"Alella","Maresme"
"Alfara de Carles","Baix Ebre"
"Alfarràs","Segrià"
"Alfés","Segrià"
"Alforja","Baix Camp"
"Algerri","Noguera"
"Alguaire","Segrià"
"Alins","Pallars Sobirà"
"Alió","Alt Camp"
"Almacelles","Segrià"
"Almatret","Segrià"
"Almenar","Segrià"
"Almoster","Baix Camp"
"Alòs de Balaguer","Noguera"
"Alp","Cerdanya"
"Alpens","Osona"
"Alpicat","Segrià"
"Alt Àneu","Pallars Sobirà"
"Altafulla","Tarragonès"
"Amer","Selva"
"Amposta","Montsià"
"Anglès","Selva"
"Anglesola","Urgell"
"Arbeca","Garrigues"
"Arbolí","Baix Camp"
"Arbúcies","Selva"
"Arenys de Mar","Maresme"
"Arenys de Munt","Maresme"
"Argelaguer","Garrotxa"
"Argençola","Anoia"
"Argentona","Maresme"
"Arnes","Terra Alta"
"Arres","Val d'Aran"
"Arsèguel","Alt Urgell"
"Artés","Bages"
"Artesa de Lleida","Segrià"
"Artesa de Segre","Noguera"
"Ascó","Ribera d'Ebre"
"Aspa","Segrià"
"Avià","Berguedà"
"Avinyó","Bages"
"Avinyonet de Puigventós","Alt Empordà"
"Avinyonet del Penedès","Alt Penedès"
"Badalona","Barcelonès"
"Badia del Vallès","Vallès Occidental"
"Bagà","Berguedà"
"Baix Pallars","Pallars Sobirà"
"Balaguer","Noguera"
"Balenyà","Osona"
"Balsareny","Bages"
"Banyeres del Penedès","Baix Penedès"
"Banyoles","Pla de l'Estany"
"Barbens","Pla d'Urgell"
"Barberà de la Conca","Conca de Barberà"
"Barberà del Vallès","Vallès Occidental"
"Barcelona","Barcelonès"
"Bàscara","Alt Empordà"
"Bassella","Alt Urgell"
"Batea","Terra Alta"
"Bausen","Val d'Aran"
"Begues","Baix Llobregat"
"Begur","Baix Empordà"
"Belianes","Urgell"
"Bell-lloc d'Urgell","Pla d'Urgell"
"Bellaguarda","Garrigues"
"Bellcaire d'Empordà","Baix Empordà"
"Bellcaire d'Urgell","Noguera"
"Bellmunt d'Urgell","Noguera"
"Bellmunt del Priorat","Priorat"
"Bellprat","Anoia"
"Bellpuig","Urgell"
"Bellvei","Baix Penedès"
"Bellver de Cerdanya","Cerdanya"
"Bellvís","Pla d'Urgell"
"Benavent de Segrià","Segrià"
"Benifallet","Baix Ebre"
"Benissanet","Ribera d'Ebre"
"Berga","Berguedà"
"Besalú","Garrotxa"
"Bescanó","Gironès"
"Beuda","Garrotxa"
"Bigues i Riells","Vallès Oriental"
"Biosca","Segarra"
"Biure","Alt Empordà"
"Blancafort","Conca de Barberà"
"Blanes","Selva"
"Boadella i les Escaules","Alt Empordà"
"Bolvir","Cerdanya"
"Bonastre","Baix Penedès"
"Bordils","Gironès"
"Borrassà","Alt Empordà"
"Borredà","Berguedà"
"Bossòst","Val d'Aran"
"Bot","Terra Alta"
"Botarell","Baix Camp"
"Bovera","Garrigues"
"Bràfim","Alt Camp"
"Breda","Selva"
"Brunyola","Selva"
"Cabacés","Priorat"
"Cabanabona","Noguera"
"Cabanelles","Alt Empordà"
"Cabanes","Alt Empordà"
"Cabó","Alt Urgell"
"Cabra del Camp","Alt Camp"
"Cabrera d'Anoia","Anoia"
"Cabrera de Mar","Maresme"
"Cabrils","Maresme"
"Cadaqués","Alt Empordà"
"Calaf","Anoia"
"Calafell","Baix Penedès"
"Calders","Moianès"
"Caldes d'Estrac","Maresme"
"Caldes de Malavella","Selva"
"Caldes de Montbui","Vallès Oriental"
"Calella","Maresme"
"Calldetenes","Osona"
"Callús","Bages"
"Calonge de Segarra","Anoia"
"Calonge i Sant Antoni","Baix Empordà"
"Camarasa","Noguera"
"Camarles","Baix Ebre"
"Cambrils","Baix Camp"
"Camós","Pla de l'Estany"
"Campdevànol","Ripollès"
"Campelles","Ripollès"
"Campins","Vallès Oriental"
"Campllong","Gironès"
"Camprodon","Ripollès"
"Canejan","Val d'Aran"
"Canet d'Adri","Gironès"
"Canet de Mar","Maresme"
"Canovelles","Vallès Oriental"
"Cànoves i Samalús","Vallès Oriental"
"Cantallops","Alt Empordà"
"Canyelles","Garraf"
"Capafonts","Baix Camp"
"Capçanes","Priorat"
"Capellades","Anoia"
"Capmany","Alt Empordà"
"Capolat","Berguedà"
"Cardedeu","Vallès Oriental"
"Cardona","Bages"
"Carme","Anoia"
"Caseres","Terra Alta"
"Cassà de la Selva","Gironès"
"Casserres","Berguedà"
"Castell de l'Areny","Berguedà"
"Castell de Mur","Pallars Jussà"
"Castell-Platja d'Aro","Baix Empordà"
"Castellar de la Ribera","Solsonès"
"Castellar de n'Hug","Berguedà"
"Castellar del Riu","Berguedà"
"Castellar del Vallès","Vallès Occidental"
"Castellbell i el Vilar","Bages"
"Castellbisbal","Vallès Occidental"
"Castellcir","Moianès"
"Castelldans","Garrigues"
"Castelldefels","Baix Llobregat"
"Castellet i la Gornal","Alt Penedès"
"Castellfollit de la Roca","Garrotxa"
"Castellfollit de Riubregós","Anoia"
"Castellfollit del Boix","Bages"
"Castellgalí","Bages"
"Castellnou de Bages","Bages"
"Castellnou de Seana","Pla d'Urgell"
"Castelló d'Empúries","Alt Empordà"
"Castelló de Farfanya","Noguera"
"Castellolí","Anoia"
"Castellserà","Urgell"
"Castellterçol","Moianès"
"Castellvell del Camp","Baix Camp"
"Castellví de la Marca","Alt Penedès"
"Castellví de Rosanes","Baix Llobregat"
"Cava","Alt Urgell"
"Celrà","Gironès"
"Centelles","Osona"
"Cercs","Berguedà"
"Cerdanyola del Vallès","Vallès Occidental"
"Cervelló","Baix Llobregat"
"Cervera","Segarra"
"Cervià de les Garrigues","Garrigues"
"Cervià de Ter","Gironès"
"Cistella","Alt Empordà"
"Ciutadilla","Urgell"
"Clariana de Cardener","Solsonès"
"Colera","Alt Empordà"
"Coll de Nargó","Alt Urgell"
"Collbató","Baix Llobregat"
"Colldejou","Baix Camp"
"Collsuspina","Moianès"
"Colomers","Baix Empordà"
"Conca de Dalt","Pallars Jussà"
"Conesa","Conca de Barberà"
"Constantí","Tarragonès"
"Copons","Anoia"
"Corbera d'Ebre","Terra Alta"
"Corbera de Llobregat","Baix Llobregat"
"Corbins","Segrià"
"Corçà","Baix Empordà"
"Cornellà de Llobregat","Baix Llobregat"
"Cornellà del Terri","Pla de l'Estany"
"Cornudella de Montsant","Priorat"
"Creixell","Tarragonès"
"Crespià","Pla de l'Estany"
"Cruïlles, Monells i Sant Sadurní de l'Heura","Baix Empordà"
"Cubelles","Garraf"
"Cubells","Noguera"
"Cunit","Baix Penedès"
"Darnius","Alt Empordà"
"Das","Cerdanya"
"Deltebre","Baix Ebre"
"Dosrius","Maresme"
"Duesaigües","Baix Camp"
"El Bruc","Anoia"
"El Brull","Osona"
"El Catllar","Tarragonès"
"El Cogul","Garrigues"
"El Far d'Empordà","Alt Empordà"
"El Lloar","Priorat"
"El Masnou","Maresme"
"El Masroig","Priorat"
"El Milà","Alt Camp"
"El Molar","Priorat"
"El Montmell","Baix Penedès"
"El Morell","Tarragonès"
"El Palau d'Anglesola","Pla d'Urgell"
"El Papiol","Baix Llobregat"
"El Perelló","Baix Ebre"
"El Pinell de Brai","Terra Alta"
"El Pla de Santa Maria","Alt Camp"
"El Pla del Penedès","Alt Penedès"
"El Poal","Pla d'Urgell"
"El Pont d'Armentera","Alt Camp"
"El Pont de Bar","Alt Urgell"
"El Pont de Suert","Alta Ribagorça"
"El Pont de Vilomara i Rocafort","Bages"
"El Port de la Selva","Alt Empordà"
"El Prat de Llobregat","Baix Llobregat"
"El Rourell","Alt Camp"
"El Soleràs","Garrigues"
"El Vendrell","Baix Penedès"
"El Vilosell","Garrigues"
"Els Alamús","Segrià"
"Els Garidells","Alt Camp"
"Els Guiamets","Priorat"
"Els Hostalets de Pierola","Anoia"
"Els Omellons","Garrigues"
"Els Omells de na Gaia","Urgell"
"Els Pallaresos","Tarragonès"
"Els Plans de Sió","Segarra"
"Els Prats de Rei","Anoia"
"Els Torms","Garrigues"
"Es Bòrdes","Val d'Aran"
"Esparreguera","Baix Llobregat"
"Espinelves","Osona"
"Esplugues de Llobregat","Baix Llobregat"
"Espolla","Alt Empordà"
"Esponellà","Pla de l'Estany"
"Espot","Pallars Sobirà"
"Estamariu","Alt Urgell"
"Estaràs","Segarra"
"Esterri d'Àneu","Pallars Sobirà"
"Esterri de Cardós","Pallars Sobirà"
"Falset","Priorat"
"Farrera","Pallars Sobirà"
"Figaró-Montmany","Vallès Oriental"
"Fígols","Berguedà"
"Fígols i Alinyà","Alt Urgell"
"Figueres","Alt Empordà"
"Figuerola del Camp","Alt Camp"
"Flaçà","Gironès"
"Flix","Ribera d'Ebre"
"Fogars de la Selva","Selva"
"Fogars de Montclús","Vallès Oriental"
"Foixà","Baix Empordà"
"Folgueroles","Osona"
"Fondarella","Pla d'Urgell"
"Fonollosa","Bages"
"Font-rubí","Alt Penedès"
"Fontanals de Cerdanya","Cerdanya"
"Fontanilles","Baix Empordà"
"Fontcoberta","Pla de l'Estany"
"Foradada","Noguera"
"Forallac","Baix Empordà"
"Forès","Conca de Barberà"
"Fornells de la Selva","Gironès"
"Fortià","Alt Empordà"
"Freginals","Montsià"
"Fulleda","Garrigues"
"Gaià","Bages"
"Gallifa","Vallès Occidental"
"Gandesa","Terra Alta"
"Garcia","Ribera d'Ebre"
"Garrigàs","Alt Empordà"
"Garrigoles","Baix Empordà"
"Garriguella","Alt Empordà"
"Gavà","Baix Llobregat"
"Gavet de la Conca","Pallars Jussà"
"Gelida","Alt Penedès"
"Ger","Cerdanya"
"Gimenells i el Pla de la Font","Segrià"
"Ginestar","Ribera d'Ebre"
"Girona","Gironès"
"Gironella","Berguedà"
"Gisclareny","Berguedà"
"Godall","Montsià"
"Golmés","Pla d'Urgell"
"Gombrèn","Ripollès"
"Gósol","Berguedà"
"Granera","Moianès"
"Granollers","Vallès Oriental"
"Granyanella","Segarra"
"Granyena de les Garrigues","Garrigues"
"Granyena de Segarra","Segarra"
"Gratallops","Priorat"
"Gualba","Vallès Oriental"
"Gualta","Baix Empordà"
"Guardiola de Berguedà","Berguedà"
"Guils de Cerdanya","Cerdanya"
"Guimerà","Urgell"
"Guissona","Segarra"
"Guixers","Solsonès"
"Gurb","Osona"
"Horta de Sant Joan","Terra Alta"
"Hostalric","Selva"
"Igualada","Anoia"
"Isona i Conca Dellà","Pallars Jussà"
"Isòvol","Cerdanya"
"Ivars d'Urgell","Pla d'Urgell"
"Ivars de Noguera","Noguera"
"Ivorra","Segarra"
"Jafre","Baix Empordà"
"Jorba","Anoia"
"Josa i Tuixén","Alt Urgell"
"Juià","Gironès"
"Juncosa","Garrigues"
"Juneda","Garrigues"
"L'Albagés","Garrigues"
"L'Albi","Garrigues"
"L'Albiol","Baix Camp"
"L'Aldea","Baix Ebre"
"L'Aleixar","Baix Camp"
"L'Ametlla de Mar","Baix Ebre"
"L'Ametlla del Vallès","Vallès Oriental"
"L'Ampolla","Baix Ebre"
"L'Arboç","Baix Penedès"
"L'Argentera","Baix Camp"
"L'Armentera","Alt Empordà"
"L'Escala","Alt Empordà"
"L'Espluga Calba","Garrigues"
"L'Espluga de Francolí","Conca de Barberà"
"L'Espunyola","Berguedà"
"L'Esquirol","Osona"
"L'Estany","Moianès"
"L'Hospitalet de Llobregat","Barcelonès"
"La Baronia de Rialb","Noguera"
"La Bisbal d'Empordà","Baix Empordà"
"La Bisbal de Montsant","Priorat"
"La Bisbal del Penedès","Baix Penedès"
"La Canonja","Tarragonès"
"La Cellera de Ter","Selva"
"La Coma i la Pedra","Solsonès"
"La Fatarella","Terra Alta"
"La Febró","Baix Camp"
"La Figuera","Priorat"
"La Floresta","Garrigues"
"La Fuliola","Urgell"
"La Galera","Montsià"
"La Garriga","Vallès Oriental"
"La Granada","Alt Penedès"
"La Granadella","Garrigues"
"La Granja d'Escarp","Segrià"
"La Guingueta d'Àneu","Pallars Sobirà"
"La Jonquera","Alt Empordà"
"La Llacuna","Anoia"
"La Llagosta","Vallès Oriental"
"La Masó","Alt Camp"
"La Molsosa","Solsonès"
"La Morera de Montsant","Priorat"
"La Nou de Berguedà","Berguedà"
"La Nou de Gaià","Tarragonès"
"La Palma d'Ebre","Ribera d'Ebre"
"La Palma de Cervelló","Baix Llobregat"
"La Pera","Baix Empordà"
"La Pobla de Cérvoles","Garrigues"
"La Pobla de Claramunt","Anoia"
"La Pobla de Lillet","Berguedà"
"La Pobla de Mafumet","Tarragonès"
"La Pobla de Massaluca","Terra Alta"
"La Pobla de Montornès","Tarragonès"
"La Pobla de Segur","Pallars Jussà"
"La Portella","Segrià"
"La Quar","Berguedà"
"la Ràpita","Montsià"
"La Riba","Alt Camp"
"La Riera de Gaià","Tarragonès"
"La Roca del Vallès","Vallès Oriental"
"La Secuita","Tarragonès"
"La Selva de Mar","Alt Empordà"
"La Selva del Camp","Baix Camp"
"La Sénia","Montsià"
"La Sentiu de Sió","Noguera"
"La Seu d'Urgell","Alt Urgell"
"La Tallada d'Empordà","Baix Empordà"
"La Torre de Capdella","Pallars Jussà"
"La Torre de Claramunt","Anoia"
"La Torre de Fontaubella","Priorat"
"La Torre de l'Espanyol","Ribera d'Ebre"
"La Vajol","Alt Empordà"
"La Vall d'en Bas","Garrotxa"
"La Vall de Bianya","Garrotxa"
"La Vall de Boí","Alta Ribagorça"
"La Vansa i Fórnols","Alt Urgell"
"La Vilella Alta","Priorat"
"La Vilella Baixa","Priorat"
"Les","Val d'Aran"
"Les Avellanes i Santa Linya","Noguera"
"Les Borges Blanques","Garrigues"
"Les Borges del Camp","Baix Camp"
"Les Cabanyes","Alt Penedès"
"Les Franqueses del Vallès","Vallès Oriental"
"Les Llosses","Ripollès"
"Les Masies de Roda","Osona"
"Les Masies de Voltregà","Osona"
"Les Oluges","Segarra"
"Les Piles","Conca de Barberà"
"Les Planes d'Hostoles","Garrotxa"
"Les Preses","Garrotxa"
"Les Valls d'Aguilar","Alt Urgell"
"Les Valls de Valira","Alt Urgell"
"Linyola","Pla d'Urgell"
"Lladó","Alt Empordà"
"Lladorre","Pallars Sobirà"
"Lladurs","Solsonès"
"Llagostera","Gironès"
"Llambilles","Gironès"
"Llanars","Ripollès"
"Llançà","Alt Empordà"
"Llardecans","Segrià"
"Llavorsí","Pallars Sobirà"
"Lleida","Segrià"
"Llers","Alt Empordà"
"Lles de Cerdanya","Cerdanya"
"Lliçà d'Amunt","Vallès Oriental"
"Lliçà de Vall","Vallès Oriental"
"Llimiana","Pallars Jussà"
"Llinars del Vallès","Vallès Oriental"
"Llívia","Cerdanya"
"Llobera","Solsonès"
"Llorac","Conca de Barberà"
"Llorenç del Penedès","Baix Penedès"
"Lloret de Mar","Selva"
"Lluçà","Osona"
"Maçanet de Cabrenys","Alt Empordà"
"Maçanet de la Selva","Selva"
"Madremanya","Gironès"
"Maià de Montcal","Garrotxa"
"Maials","Segrià"
"Maldà","Urgell"
"Malgrat de Mar","Maresme"
"Malla","Osona"
"Manlleu","Osona"
"Manresa","Bages"
"Marçà","Priorat"
"Margalef","Priorat"
"Marganell","Bages"
"Martorell","Baix Llobregat"
"Martorelles","Vallès Oriental"
"Mas de Barberans","Montsià"
"Masarac","Alt Empordà"
"Masdenverge","Montsià"
"Masllorenç","Baix Penedès"
"Maspujols","Baix Camp"
"Masquefa","Anoia"
"Massalcoreig","Segrià"
"Massanes","Selva"
"Massoteres","Segarra"
"Matadepera","Vallès Occidental"
"Mataró","Maresme"
"Medinyà","Gironès"
"Mediona","Alt Penedès"
"Menàrguens","Noguera"
"Meranges","Cerdanya"
"Mieres","Garrotxa"
"Miralcamp","Pla d'Urgell"
"Miravet","Ribera d'Ebre"
"Moià","Moianès"
"Molins de Rei","Baix Llobregat"
"Mollerussa","Pla d'Urgell"
"Mollet de Peralada","Alt Empordà"
"Mollet del Vallès","Vallès Oriental"
"Molló","Ripollès"
"Monistrol de Calders","Moianès"
"Monistrol de Montserrat","Bages"
"Mont-ral","Alt Camp"
"Mont-ras","Baix Empordà"
"Mont-roig del Camp","Baix Camp"
"Montagut i Oix","Garrotxa"
"Montblanc","Conca de Barberà"
"Montbrió del Camp","Baix Camp"
"Montcada i Reixac","Vallès Occidental"
"Montclar","Berguedà"
"Montellà i Martinet","Cerdanya"
"Montesquiu","Osona"
"Montferrer i Castellbò","Alt Urgell"
"Montferri","Alt Camp"
"Montgai","Noguera"
"Montferrer i Castellbò","Alt Urgell"
"Montferri","Alt Camp"
"Montgai","Noguera"
"Montgat","Maresme"
"Montmajor","Berguedà"
"Montmaneu","Anoia"
"Montmeló","Vallès Oriental"
"Montoliu de Lleida","Segrià"
"Montoliu de Segarra","Segarra"
"Montornès de Segarra","Segarra"
"Montornès del Vallès","Vallès Oriental"
"Montseny","Vallès Oriental"
"Móra d'Ebre","Ribera d'Ebre"
"Móra la Nova","Ribera d'Ebre"
"Muntanyola","Osona"
"Mura","Bages"
"Nalec","Urgell"
"Naut Aran","Val d'Aran"
"Navarcles","Bages"
"Navàs","Bages"
"Navata","Alt Empordà"
"Navès","Solsonès"
"Nulles","Alt Camp"
"Odèn","Solsonès"
"Òdena","Anoia"
"Ogassa","Ripollès"
"Olèrdola","Alt Penedès"
"Olesa de Bonesvalls","Alt Penedès"
"Olesa de Montserrat","Baix Llobregat"
"Oliana","Alt Urgell"
"Oliola","Noguera"
"Olius","Solsonès"
"Olivella","Garraf"
"Olost","Osona"
"Olot","Garrotxa"
"Olvan","Berguedà"
"Ordis","Alt Empordà"
"Organyà","Alt Urgell"
"Orís","Osona"
"Oristà","Osona"
"Orpí","Anoia"
"Òrrius","Maresme"
"Os de Balaguer","Noguera"
"Osor","Selva"
"Ossó de Sió","Urgell"
"Pacs del Penedès","Alt Penedès"
"Palafolls","Maresme"
"Palafrugell","Baix Empordà"
"Palamós","Baix Empordà"
"Palau de Santa Eulàlia","Alt Empordà"
"Palau-sator","Baix Empordà"
"Palau-saverdera","Alt Empordà"
"Palau-solità i Plegamans","Vallès Occidental"
"Pallejà","Baix Llobregat"
"Palol de Revardit","Pla de l'Estany"
"Pals","Baix Empordà"
"Pardines","Ripollès"
"Parets del Vallès","Vallès Oriental"
"Parlavà","Baix Empordà"
"Passanant i Belltall","Conca de Barberà"
"Pau","Alt Empordà"
"Paüls","Baix Ebre"
"Pedret i Marzà","Alt Empordà"
"Penelles","Noguera"
"Perafita","Osona"
"Perafort","Tarragonès"
"Peralada","Alt Empordà"
"Peramola","Alt Urgell"
"Piera","Anoia"
"Pineda de Mar","Maresme"
"Pinell de Solsonès","Solsonès"
"Pinós","Solsonès"
"Pira","Conca de Barberà"
"Planoles","Ripollès"
"Poboleda","Priorat"
"Polinyà","Vallès Occidental"
"Pont de Molins","Alt Empordà"
"Pontils","Conca de Barberà"
"Pontons","Alt Penedès"
"Pontós","Alt Empordà"
"Ponts","Noguera"
"Porqueres","Pla de l'Estany"
"Porrera","Priorat"
"Portbou","Alt Empordà"
"Pradell de la Teixeta","Priorat"
"Prades","Baix Camp"
"Prat de Comte","Terra Alta"
"Pratdip","Baix Camp"
"Prats de Lluçanès","Osona"
"Prats i Sansor","Cerdanya"
"Preixana","Urgell"
"Preixens","Noguera"
"Premià de Dalt","Maresme"
"Premià de Mar","Maresme"
"Prullans","Cerdanya"
"Puig-reig","Berguedà"
"Puigcerdà","Cerdanya"
"Puigdàlber","Alt Penedès"
"Puiggròs","Garrigues"
"Puigpelat","Alt Camp"
"Puigverd d'Agramunt","Urgell"
"Puigverd de Lleida","Segrià"
"Pujalt","Anoia"
"Quart","Gironès"
"Queralbs","Ripollès"
"Querol","Alt Camp"
"Rabós","Alt Empordà"
"Rajadell","Bages"
"Rasquera","Ribera d'Ebre"
"Regencós","Baix Empordà"
"Rellinars","Vallès Occidental"
"Renau","Tarragonès"
"Reus","Baix Camp"
"Rialp","Pallars Sobirà"
"Riba-roja d'Ebre","Ribera d'Ebre"
"Ribera d'Ondara","Segarra"
"Ribera d'Urgellet","Alt Urgell"
"Ribes de Freser","Ripollès"
"Riells i Viabrea","Selva"
"Riner","Solsonès"
"Ripoll","Ripollès"
"Ripollet","Vallès Occidental"
"Riu de Cerdanya","Cerdanya"
"Riudarenes","Selva"
"Riudaura","Garrotxa"
"Riudecanyes","Baix Camp"
"Riudecols","Baix Camp"
"Riudellots de la Selva","Selva"
"Riudoms","Baix Camp"
"Riumors","Alt Empordà"
"Rocafort de Queralt","Conca de Barberà"
"Roda de Berà","Tarragonès"
"Roda de Ter","Osona"
"Rodonyà","Alt Camp"
"Roquetes","Baix Ebre"
"Roses","Alt Empordà"
"Rosselló","Segrià"
"Rubí","Vallès Occidental"
"Rubió","Anoia"
"Rupià","Baix Empordà"
"Rupit i Pruit","Osona"
"Sabadell","Vallès Occidental"
"Sagàs","Berguedà"
"Salàs de Pallars","Pallars Jussà"
"Saldes","Berguedà"
"Sales de Llierca","Garrotxa"
"Sallent","Bages"
"Salomó","Tarragonès"
"Salou","Tarragonès"
"Salt","Gironès"
"Sanaüja","Segarra"
"Sant Adrià de Besòs","Barcelonès"
"Sant Agustí de Lluçanès","Osona"
"Sant Andreu de la Barca","Baix Llobregat"
"Sant Andreu de Llavaneres","Maresme"
"Sant Andreu Salou","Gironès"
"Sant Aniol de Finestres","Garrotxa"
"Sant Antoni de Vilamajor","Vallès Oriental"
"Sant Bartomeu del Grau","Osona"
"Sant Boi de Llobregat","Baix Llobregat"
"Sant Boi de Lluçanès","Osona"
"Sant Cebrià de Vallalta","Maresme"
"Sant Celoni","Vallès Oriental"
"Sant Climent de Llobregat","Baix Llobregat"
"Sant Climent Sescebes","Alt Empordà"
"Sant Cugat del Vallès","Vallès Occidental"
"Sant Cugat Sesgarrigues","Alt Penedès"
"Sant Esteve de la Sarga","Pallars Jussà"
"Sant Esteve de Palautordera","Vallès Oriental"
"Sant Esteve Sesrovires","Baix Llobregat"
"Sant Feliu de Buixalleu","Selva"
"Sant Feliu de Codines","Vallès Oriental"
"Sant Feliu de Guíxols","Baix Empordà"
"Sant Feliu de Llobregat","Baix Llobregat"
"Sant Feliu de Pallerols","Garrotxa"
"Sant Feliu Sasserra","Bages"
"Sant Ferriol","Garrotxa"
"Sant Fost de Campsentelles","Vallès Oriental"
"Sant Fruitós de Bages","Bages"
"Sant Gregori","Gironès"
"Sant Guim de Freixenet","Segarra"
"Sant Guim de la Plana","Segarra"
"Sant Hilari Sacalm","Selva"
"Sant Hipòlit de Voltregà","Osona"
"Sant Iscle de Vallalta","Maresme"
"Sant Jaume d'Enveja","Montsià"
"Sant Jaume de Frontanyà","Berguedà"
"Sant Jaume de Llierca","Garrotxa"
"Sant Jaume dels Domenys","Baix Penedès"
"Sant Joan de les Abadesses","Ripollès"
"Sant Joan de Mollet","Gironès"
"Sant Joan de Vilatorrada","Bages"
"Sant Joan Despí","Baix Llobregat"
"Sant Joan les Fonts","Garrotxa"
"Sant Jordi Desvalls","Gironès"
"Sant Julià de Cerdanyola","Berguedà"
"Sant Julià de Ramis","Gironès"
"Sant Julià de Vilatorta","Osona"
"Sant Julià del Llor i Bonmatí","Selva"
"Sant Just Desvern","Baix Llobregat"
"Sant Llorenç d'Hortons","Alt Penedès"
"Sant Llorenç de la Muga","Alt Empordà"
"Sant Llorenç de Morunys","Solsonès"
"Sant Llorenç Savall","Vallès Occidental"
"Sant Martí d'Albars","Osona"
"Sant Martí de Centelles","Osona"
"Sant Martí de Llémena","Gironès"
"Sant Martí de Riucorb","Urgell"
"Sant Martí de Tous","Anoia"
"Sant Martí Sarroca","Alt Penedès"
"Sant Martí Sesgueioles","Anoia"
"Sant Martí Vell","Gironès"
"Sant Mateu de Bages","Bages"
"Sant Miquel de Campmajor","Pla de l'Estany"
"Sant Miquel de Fluvià","Alt Empordà"
"Sant Mori","Alt Empordà"
"Sant Pau de Segúries","Ripollès"
"Sant Pere de Ribes","Garraf"
"Sant Pere de Riudebitlles","Alt Penedès"
"Sant Pere de Torelló","Osona"
"Sant Pere de Vilamajor","Vallès Oriental"
"Sant Pere Pescador","Alt Empordà"
"Sant Pere Sallavinera","Anoia"
"Sant Pol de Mar","Maresme"
"Sant Quintí de Mediona","Alt Penedès"
"Sant Quirze de Besora","Osona"
"Sant Quirze del Vallès","Vallès Occidental"
"Sant Quirze Safaja","Moianès"
"Sant Ramon","Segarra"
"Sant Sadurní d'Anoia","Alt Penedès"
"Sant Sadurní d'Osormort","Osona"
"Sant Salvador de Guardiola","Bages"
"Sant Vicenç de Castellet","Bages"
"Sant Vicenç de Montalt","Maresme"
"Sant Vicenç de Torelló","Osona"
"Sant Vicenç dels Horts","Baix Llobregat"
"Santa Bàrbara","Montsià"
"Santa Cecília de Voltregà","Osona"
"Santa Coloma de Cervelló","Baix Llobregat"
"Santa Coloma de Farners","Selva"
"Santa Coloma de Gramenet","Barcelonès"
"Santa Coloma de Queralt","Conca de Barberà"
"Santa Cristina d'Aro","Baix Empordà"
"Santa Eugènia de Berga","Osona"
"Santa Eulàlia de Riuprimer","Osona"
"Santa Eulàlia de Ronçana","Vallès Oriental"
"Santa Fe del Penedès","Alt Penedès"
"Santa Llogaia d'Àlguema","Alt Empordà"
"Santa Margarida de Montbui","Anoia"
"Santa Margarida i els Monjos","Alt Penedès"
"Santa Maria d'Oló","Moianès"
"Santa Maria de Besora","Osona"
"Santa Maria de Martorelles","Vallès Oriental"
"Santa Maria de Merlès","Berguedà"
"Santa Maria de Miralles","Anoia"
"Santa Maria de Palautordera","Vallès Oriental"
"Santa Oliva","Baix Penedès"
"Santa Pau","Garrotxa"
"Santa Perpètua de Mogoda","Vallès Occidental"
"Santa Susanna","Maresme"
"Santpedor","Bages"
"Sarral","Conca de Barberà"
"Sarrià de Ter","Gironès"
"Sarroca de Bellera","Pallars Jussà"
"Sarroca de Lleida","Segrià"
"Saus, Camallera i Llampaies","Alt Empordà"
"Savallà del Comtat","Conca de Barberà"
"Senan","Conca de Barberà"
"Senterada","Pallars Jussà"
"Sentmenat","Vallès Occidental"
"Serinyà","Pla de l'Estany"
"Seròs","Segrià"
"Serra de Daró","Baix Empordà"
"Setcases","Ripollès"
"Seva","Osona"
"Sidamon","Pla d'Urgell"
"Sils","Selva"
"Sitges","Garraf"
"Siurana","Alt Empordà"
"Sobremunt","Osona"
"Solivella","Conca de Barberà"
"Solsona","Solsonès"
"Sora","Osona"
"Soriguera","Pallars Sobirà"
"Sort","Pallars Sobirà"
"Soses","Segrià"
"Subirats","Alt Penedès"
"Sudanell","Segrià"
"Sunyer","Segrià"
"Súria","Bages"
"Susqueda","Selva"
"Tagamanent","Vallès Oriental"
"Talamanca","Bages"
"Talarn","Pallars Jussà"
"Talavera","Segarra"
"Taradell","Osona"
"Tarragona","Tarragonès"
"Tàrrega","Urgell"
"Tarrés","Garrigues"
"Tarroja de Segarra","Segarra"
"Tavèrnoles","Osona"
"Tavertet","Osona"
"Teià","Maresme"
"Térmens","Noguera"
"Terrades","Alt Empordà"
"Terrassa","Vallès Occidental"
"Tiana","Maresme"
"Tírvia","Pallars Sobirà"
"Tiurana","Noguera"
"Tivenys","Baix Ebre"
"Tivissa","Ribera d'Ebre"
"Tona","Osona"
"Torà","Segarra"
"Tordera","Maresme"
"Torelló","Osona"
"Tornabous","Urgell"
"Torre-serona","Segrià"
"Torrebesses","Segrià"
"Torredembarra","Tarragonès"
"Torrefarrera","Segrià"
"Torrefeta i Florejacs","Segarra"
"Torregrossa","Pla d'Urgell"
"Torrelameu","Noguera"
"Torrelavit","Alt Penedès"
"Torrelles de Foix","Alt Penedès"
"Torrelles de Llobregat","Baix Llobregat"
"Torrent","Baix Empordà"
"Torres de Segre","Segrià"
"Torroella de Fluvià","Alt Empordà"
"Torroella de Montgrí i l'Estartit","Baix Empordà"
"Torroja del Priorat","Priorat"
"Tortellà","Garrotxa"
"Tortosa","Baix Ebre"
"Toses","Ripollès"
"Tossa de Mar","Selva"
"Tremp","Pallars Jussà"
"Ullà","Baix Empordà"
"Ullastrell","Vallès Occidental"
"Ullastret","Baix Empordà"
"Ulldecona","Montsià"
"Ulldemolins","Priorat"
"Ultramort","Baix Empordà"
"Urús","Cerdanya"
"Vacarisses","Vallès Occidental"
"Vall de Cardós","Pallars Sobirà"
"Vall-llobrega","Baix Empordà"
"Vallbona d'Anoia","Anoia"
"Vallbona de les Monges","Urgell"
"Vallcebre","Berguedà"
"Vallclara","Conca de Barberà"
"Vallfogona de Balaguer","Noguera"
"Vallfogona de Ripollès","Ripollès"
"Vallfogona de Riucorb","Conca de Barberà"
"Vallgorguina","Vallès Oriental"
"Vallirana","Baix Llobregat"
"Vallmoll","Alt Camp"
"Vallromanes","Vallès Oriental"
"Valls","Alt Camp"
"Vandellòs i l'Hospitalet de l'Infant","Baix Camp"
"Veciana","Anoia"
"Ventalló","Alt Empordà"
"Verdú","Urgell"
"Verges","Baix Empordà"
"Vespella de Gaià","Tarragonès"
"Vic","Osona"
"Vidrà","Osona"
"Vidreres","Selva"
"Vielha e Mijaran","Val d'Aran"
"Vila-rodona","Alt Camp"
"Vila-sacra","Alt Empordà"
"Vila-sana","Pla d'Urgell"
"Vila-seca","Tarragonès"
"Vilabella","Alt Camp"
"Vilabertran","Alt Empordà"
"Vilablareix","Gironès"
"Vilada","Berguedà"
"Viladamat","Alt Empordà"
"Viladasens","Gironès"
"Viladecans","Baix Llobregat"
"Viladecavalls","Vallès Occidental"
"Vilademuls","Pla de l'Estany"
"Viladrau","Osona"
"Vilafant","Alt Empordà"
"Vilafranca del Penedès","Alt Penedès"
"Vilagrassa","Urgell"
"Vilajuïga","Alt Empordà"
"Vilalba dels Arcs","Terra Alta"
"Vilalba Sasserra","Vallès Oriental"
"Vilaller","Alta Ribagorça"
"Vilallonga de Ter","Ripollès"
"Vilallonga del Camp","Tarragonès"
"Vilamacolum","Alt Empordà"
"Vilamalla","Alt Empordà"
"Vilamaniscle","Alt Empordà"
"Vilamòs","Val d'Aran"
"Vilanant","Alt Empordà"
"Vilanova d'Escornalbou","Baix Camp"
"Vilanova de Bellpuig","Pla d'Urgell"
"Vilanova de l'Aguda","Noguera"
"Vilanova de la Barca","Segrià"
"Vilanova de Meià","Noguera"
"Vilanova de Prades","Conca de Barberà"
"Vilanova de Sau","Osona"
"Vilanova de Segrià","Segrià"
"Vilanova del Camí","Anoia"
"Vilanova del Vallès","Vallès Oriental"
"Vilanova i la Geltrú","Garraf"
"Vilaplana","Baix Camp"
"Vilassar de Dalt","Maresme"
"Vilassar de Mar","Maresme"
"Vilaür","Alt Empordà"
"Vilaverd","Conca de Barberà"
"Vilobí d'Onyar","Selva"
"Vilobí del Penedès","Alt Penedès"
"Vilopriu","Baix Empordà"
"Vimbodí i Poblet","Conca de Barberà"
"Vinaixa","Garrigues"
"Vinebre","Ribera d'Ebre"
"Vinyols i els Arcs","Baix Camp"
"Viver i Serrateix","Berguedà"
"Xerta","Baix Ebre"`;

async function seed() {
    const lines = RawCSV.trim().split("\n").slice(1);
    const total = lines.length;
    console.log(`🚀 Iniciant seed de ${total} municipis...`);

    // Batch entries for performance
    const batchSize = 100;
    for (let i = 0; i < lines.length; i += batchSize) {
        const batchLines = lines.slice(i, i + batchSize);
        const entries = batchLines.map(line => {
            // Regex per capturar text entre cometes
            const match = line.match(/"([^"]+)"\s*,\s*"([^"]+)"/);
            if (!match) return null;

            const [_, nom, comarca] = match;
            return {
                nom,
                comarca,
                nom_normalitzat: normalizePlace(nom),
                pais: "ES",
                region: "Catalunya"
            };
        }).filter(Boolean);

        if (entries.length === 0) continue;

        const { error } = await supabase
            .from("municipis")
            .upsert(entries, {
                onConflict: "nom_normalitzat, pais, region"
            });

        if (error) {
            console.error(`❌ Error al batch starting at ${i}:`, error.message);
        } else {
            console.log(`✅ Processats ${Math.min(i + batchSize, total)}/${total}...`);
        }
    }

    console.log("✨ Seed finalitzat corectament!");
}

seed().catch(err => {
    console.error("Fatal Error:", err);
    process.exit(1);
});
